name: Changesets

on:
  push:
    branches:
      - main
    paths:
      - ".changeset/**/*.md"
      - "packages/**/package.json"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # - name: Generate npmrc config file
      #   run: |
      #     echo -e "@for-study:registry=${{ secrets.NPM_REGISTRY }}\n${{ secrets.NPM_REGISTRY }}:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      #     echo "===== .npmrc contents ====="
      #     cat .npmrc
      #     echo "===== files ====="
      #     ls -la

      - name: Create PR and publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          commit: "chore(changeset): update versions"
          title: "chore(changeset): update versions"
          publish: pnpm changeset publish --tag
